---
all:
  children:
    api_1_replicaset:
      hosts:
        API-1: ~
      vars:
        failover_priority:
          - API-1
        leader: API-1
        replicaset_alias: API-1
        roles:
          - app.roles.adg_api
          - vshard-router
    host1:
      hosts:
        API-1:
          config:
            advertise_uri: "localhost:3301"
            http_port: 8081
        INPUT-PROCESSOR-1:
          config:
            advertise_uri: "localhost:3302"
            http_port: 8082
        KAFKA-1:
          config:
            advertise_uri: "localhost:3303"
            http_port: 8083
        MASTER-1:
          config:
            advertise_uri: "localhost:3304"
            http_port: 8084
        OUTPUT-PROCESSOR-1:
          config:
            advertise_uri: "localhost:3305"
            http_port: 8085
        STATE-1:
          config:
            advertise_uri: "localhost:3315"
            http_port: 8086
      vars:
        ansible_connection: local
        ansible_host: localhost
        ansible_user: root
    input_1_replicaset:
      hosts:
        INPUT-PROCESSOR-1:
      vars:
        failover_priority:
          - INPUT-PROCESSOR-1
        leader: INPUT-PROCESSOR-1
        replicaset_alias: INPUT-PROCESSOR-1
        roles:
          - app.roles.adg_input_processor
          - vshard-router
    kafka_1_replicaset:
      hosts:
        KAFKA-1:
      vars:
        failover_priority:
          - KAFKA-1
        leader: KAFKA-1
        replicaset_alias: KAFKA-1
        roles:
          - app.roles.adg_kafka_connector
          - vshard-router
    output_1_replicaset:
      hosts:
        OUTPUT-PROCESSOR-1:
      vars:
        failover_priority:
          - OUTPUT-PROCESSOR-1
        leader: OUTPUT-PROCESSOR-1
        replicaset_alias: OUTPUT-PROCESSOR-1
        roles:
          - app.roles.adg_output_processor
          - vshard-router
    storage_1_replicaset:
      hosts:
        MASTER-1:
      vars:
        failover_priority:
          - MASTER-1
        leader: MASTER-1
        replicaset_alias: STORAGE-1
        roles:
          - app.roles.adg_storage
          - vshard-storage
    state_1_replicaset:
      hosts:
        STATE-1:
      vars:
        failover_priority:
          - STATE-1
        leader: STATE-1
        replicaset_alias: STATE-1
        roles:
          - app.roles.adg_state
          - vshard-router
  vars:
    cartridge_app_config:
      etl_scd:
        body:
          start_field_nm: "sys_from"
          end_field_nm: "sys_to"
          op_field_nm: "sys_op"
      kafka_bootstrap:
        body:
          bootstrap_connection_string: "10.92.6.44:9092"
      kafka_consume:
        body:
          custom_properties:
            log_level: 7
          properties:
            auto.offset.reset: "earliest"
            enable.auto.commit: "false"
            enable.auto.offset.store: "false"
            group.id: "tarantool-group-csv"
          topics:
            - EMPLOYEES
              TEST
      kafka_produce:
        body:
          custom_properties:
            log_level: 7
          properties:
      kafka_topics:
        body:
          EMPLOYEES:
            error_topic: err
            schema_data: employees
            schema_key: adb_upload_request
            success_topic: succ
            target_table: EMPLOYEES
      schema:
        body:
          spaces:
            TEST_TABLE:
              engine: memtx
              format:
                -
                  is_nullable: false
                  name: TEST_TABLE_UID
                  type: string
                -
                  is_nullable: false
                  name: TEST_TABLE_DATE
                  type: number
                -
                  is_nullable: false
                  name: TEST_TABLE_STRING
                  type: string
                -
                  is_nullable: false
                  name: TEST_TABLE_NUMBER
                  type: number
                -
                  is_nullable: true
                  name: TEST_TABLE_NULL
                  type: string
                -
                  is_nullable: false
                  name: bucket_id
                  type: unsigned
              indexes:
                -
                  name: TEST_TABLE_UID
                  parts:
                    -
                      is_nullable: false
                      path: TEST_TABLE_UID
                      type: string
                  type: TREE
                  unique: true
                -
                  name: bucket_id
                  parts:
                    -
                      is_nullable: false
                      path: bucket_id
                      type: unsigned
                  type: TREE
                  unique: false
              is_local: false
              sharding_key:
                - TEST_TABLE_UID
              temporary: false
            TEST_TABLE2:
              engine: memtx
              format:
                -
                  is_nullable: false
                  name: TEST_TABLE_UID
                  type: string
                -
                  is_nullable: false
                  name: TEST_TABLE_DATE
                  type: number
                -
                  is_nullable: false
                  name: TEST_TABLE_STRING
                  type: string
                -
                  is_nullable: false
                  name: TEST_TABLE_NUMBER
                  type: number
                -
                  is_nullable: true
                  name: TEST_TABLE_NULL
                  type: string
                -
                  is_nullable: false
                  name: bucket_id
                  type: unsigned
              indexes:
                -
                  name: TEST_TABLE_UID
                  parts:
                    -
                      is_nullable: false
                      path: TEST_TABLE_UID
                      type: string
                  type: TREE
                  unique: true
                -
                  name: bucket_id
                  parts:
                    -
                      is_nullable: false
                      path: bucket_id
                      type: unsigned
                  type: TREE
                  unique: false
              is_local: false
              sharding_key:
                - TEST_TABLE_UID
              temporary: false
    cartridge_app_name: memstorage
    cartridge_bootstrap_vshard: true
    cartridge_cluster_cookie: memstorage-cluster-cookie
    cartridge_defaults:
      log_level: 5
    cartridge_package_path: /home/ashitov/adg_nsud/memstorage-0.1.2-0.rpm
